// The meteor showers: the major showers of the International Meteor
// Organization's calendar, and a few minor ones worth a look.
//
//   code    IMO code
//   from/to the dates the shower is active [month, day]
//   sl      solar longitude of the peak (degrees, J2000): the Earth crosses
//           the densest part of the stream at the same point of its orbit
//           every year, so the date of the peak is found from the Sun
//   zhr     zenithal hourly rate at the peak: the meteors one observer would
//           see in an hour under a perfectly dark sky (magnitude 6.5) with
//           the radiant overhead
//   b       how fast the activity falls away from the peak (degrees of solar
//           longitude to fall to 1/e = 37%)
//   ra/dec  the radiant at the peak (degrees)
//   v       speed of the meteors entering the air (km/s)
//   r       population index: how many more faint meteors there are for each
//           magnitude (higher: fewer bright ones)
//   con     constellation of the radiant
//   parent  the comet (or asteroid) that left the dust

const SHOWERS = [
  {
    id: "qua",
    code: "QUA",
    name: "Quadrantids",
    from: [12, 28],
    to: [1, 12],
    sl: 283.15,
    zhr: 80,
    b: 0.45,
    ra: 230,
    dec: 49,
    v: 41,
    r: 2.1,
    con: "Boötes",
    parent: "2003 EH1, an asteroid that was probably a comet",
    about:
      "One of the strongest showers of the year, but its peak lasts only a few hours, so it is easy to miss. The radiant is in the north, near the handle of the Big Dipper, in a constellation that no longer exists: Quadrans Muralis, the wall quadrant, which gave the shower its name.",
  },
  {
    id: "ace",
    code: "ACE",
    name: "Alpha Centaurids",
    from: [1, 31],
    to: [2, 20],
    sl: 319.2,
    zhr: 6,
    b: 1.5,
    ra: 210,
    dec: -59,
    v: 56,
    r: 2.0,
    con: "Centaurus",
    parent: "unknown",
    about:
      "A southern shower, from next to Alpha and Beta Centauri, the pointers of the Southern Cross. Usually modest, it has given bright fireballs and short outbursts. From most of the northern hemisphere, the radiant never rises.",
  },
  {
    id: "lyr",
    code: "LYR",
    name: "Lyrids",
    from: [4, 14],
    to: [4, 30],
    sl: 32.32,
    zhr: 18,
    b: 0.9,
    ra: 271,
    dec: 34,
    v: 49,
    r: 2.1,
    con: "Lyra",
    parent: "comet C/1861 G1 (Thatcher)",
    about:
      "The oldest recorded shower: Chinese astronomers saw it in 687 BC, when \"stars fell like rain\". It ends the long lull of early spring, with fast, bright meteors from near Vega, and sometimes an outburst of up to a hundred an hour, as in 1982.",
  },
  {
    id: "eta",
    code: "ETA",
    name: "Eta Aquariids",
    from: [4, 19],
    to: [5, 28],
    sl: 45.5,
    zhr: 50,
    b: 3,
    ra: 338,
    dec: -1,
    v: 66,
    r: 2.4,
    con: "Aquarius",
    parent: "comet 1P/Halley",
    about:
      "Dust of Halley's comet, met on the way in. The radiant rises only an hour or two before dawn, so the shower is best from the southern hemisphere and the tropics, where it is one of the year's finest. Its meteors are fast and often leave glowing trains.",
  },
  {
    id: "sda",
    code: "SDA",
    name: "Southern Delta Aquariids",
    from: [7, 12],
    to: [8, 23],
    sl: 127,
    zhr: 25,
    b: 3,
    ra: 340,
    dec: -16,
    v: 41,
    r: 2.5,
    con: "Aquarius",
    parent: "comet 96P/Machholz",
    about:
      "A long, steady shower of the warm nights of July, mostly faint meteors from low in the south. It overlaps the start of the Perseids, so a late July night shows meteors from two directions: watch where they come from.",
  },
  {
    id: "cap",
    code: "CAP",
    name: "Alpha Capricornids",
    from: [7, 3],
    to: [8, 15],
    sl: 127,
    zhr: 5,
    b: 4,
    ra: 307,
    dec: -10,
    v: 23,
    r: 2.5,
    con: "Capricornus",
    parent: "comet 169P/NEAT",
    about:
      "Few meteors, but slow and bright ones, with more fireballs than any other shower. They enter the air at only 23 km/s, so they glide across the sky for a second or more.",
  },
  {
    id: "per",
    code: "PER",
    name: "Perseids",
    from: [7, 17],
    to: [8, 24],
    sl: 140.0,
    zhr: 100,
    b: 1.0,
    ra: 48,
    dec: 58,
    v: 59,
    r: 2.2,
    con: "Perseus",
    parent: "comet 109P/Swift-Tuttle",
    about:
      "The favorite shower of the northern summer: warm nights, a high radiant and plenty of bright meteors. In Catholic Europe they were the \"tears of Saint Lawrence\", whose feast day is August 10. Their comet, Swift-Tuttle, 26 km wide, comes back in 2126.",
  },
  {
    id: "dra",
    code: "DRA",
    name: "Draconids",
    from: [10, 6],
    to: [10, 10],
    sl: 195.4,
    zhr: 5,
    b: 0.5,
    ra: 262,
    dec: 54,
    v: 20,
    r: 2.6,
    con: "Draco",
    parent: "comet 21P/Giacobini-Zinner",
    about:
      "Usually only a few slow meteors, but a shower of surprises: it gave storms of thousands an hour in 1933 and 1946, and outbursts in 2011 and 2018. The radiant is highest in the evening, so it is the one shower to watch before midnight.",
  },
  {
    id: "sta",
    code: "STA",
    name: "Southern Taurids",
    from: [9, 10],
    to: [11, 20],
    sl: 197,
    zhr: 5,
    b: 10,
    ra: 32,
    dec: 9,
    v: 27,
    r: 2.3,
    con: "Cetus",
    parent: "comet 2P/Encke",
    about:
      "A wide, slow stream of large grains, active for weeks at a low rate, with its northern twin. Every few years (the \"swarm years\", such as 2032 and 2036) the Earth crosses a clump of it and the Taurids give many fireballs: the Halloween fireballs.",
  },
  {
    id: "ori",
    code: "ORI",
    name: "Orionids",
    from: [10, 2],
    to: [11, 7],
    sl: 208,
    zhr: 20,
    b: 2.5,
    ra: 95,
    dec: 16,
    v: 66,
    r: 2.5,
    con: "Orion",
    parent: "comet 1P/Halley",
    about:
      "The other shower of Halley's comet, met on its way out. Fast meteors, many with trains, from above Orion's shoulder, Betelgeuse. The peak is broad, so the nights around it are almost as good.",
  },
  {
    id: "nta",
    code: "NTA",
    name: "Northern Taurids",
    from: [10, 20],
    to: [12, 10],
    sl: 230,
    zhr: 5,
    b: 10,
    ra: 58,
    dec: 22,
    v: 29,
    r: 2.3,
    con: "Taurus",
    parent: "comet 2P/Encke",
    about:
      "The northern half of the Taurid stream, taking over from the southern one in November, near the Pleiades. Slow, often bright, and sometimes a fireball that lights up the ground.",
  },
  {
    id: "leo",
    code: "LEO",
    name: "Leonids",
    from: [11, 6],
    to: [11, 30],
    sl: 235.27,
    zhr: 15,
    b: 1.0,
    ra: 152,
    dec: 22,
    v: 71,
    r: 2.5,
    con: "Leo",
    parent: "comet 55P/Tempel-Tuttle",
    about:
      "The fastest meteors of all, 71 km/s, from the Sickle of Leo. Most years they are modest, but when their comet comes back every 33 years the Leonids can storm: tens of thousands an hour in 1833, which started the science of meteors, and in 1966, and thousands in 1999 to 2002.",
  },
  {
    id: "gem",
    code: "GEM",
    name: "Geminids",
    from: [12, 4],
    to: [12, 20],
    sl: 262.2,
    zhr: 150,
    b: 1.0,
    ra: 112,
    dec: 33,
    v: 35,
    r: 2.6,
    con: "Gemini",
    parent: "3200 Phaethon, a rocky asteroid",
    about:
      "The richest shower of the year, and getting stronger. Its parent is not a comet but a rock, Phaethon, so the meteors are dense, slow and bright, often colored. The radiant, near Castor, is up most of the night, so the show starts in the evening.",
  },
  {
    id: "urs",
    code: "URS",
    name: "Ursids",
    from: [12, 17],
    to: [12, 26],
    sl: 270.7,
    zhr: 10,
    b: 0.5,
    ra: 217,
    dec: 76,
    v: 33,
    r: 3.0,
    con: "Ursa Minor",
    parent: "comet 8P/Tuttle",
    about:
      "A small shower around the winter solstice, from near the Little Dipper, so its radiant never sets for most of the northern hemisphere. Usually ten an hour, with the odd outburst.",
  },
];
